# Generated by Django 2.1.3 on 2021-07-31 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('desc', models.CharField(max_length=100, verbose_name='简要介绍')),
                ('responsible', models.CharField(max_length=20, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目信息',
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='报告名称')),
                ('type', models.IntegerField(choices=[(1, '调试'), (2, '异步'), (3, '定时'), (4, 'WebUI')], verbose_name='报告类型')),
                ('summary', models.TextField(verbose_name='主体信息')),
                ('executor_name', models.CharField(default='', max_length=50, null=True, verbose_name='执行人')),
                ('execution_name', models.CharField(default='null', max_length=100, verbose_name='报告所属的api/case/task名称')),
                ('execution_id', models.IntegerField(default=0, verbose_name='报告所属的api/case/task的id')),
                ('execution_type', models.IntegerField(choices=[(0, 'Task'), (1, 'Api'), (2, 'Case'), (3, '公共Case'), (4, '失败重试'), (5, 'CICD任务')], default=0, verbose_name='报告所属的api/case/task的类型')),
                ('run_status', models.IntegerField(choices=[(0, '运行中'), (1, '已完成')], default=0, verbose_name='运行状态')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stlapp.Project')),
            ],
            options={
                'verbose_name': '测试报告',
                'db_table': 'Report',
            },
        ),
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('summary', models.TextField(verbose_name='主体信息')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stlapp.Report')),
            ],
            options={
                'verbose_name': '报告详情',
                'db_table': 'reportsummary',
            },
        ),
    ]
