# Generated by Django 2.1.3 on 2021-07-31 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('real_name', models.CharField(max_length=20, null=True, verbose_name='真实姓名')),
                ('password', models.CharField(max_length=100, verbose_name='登陆密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='用户邮箱')),
                ('user_type', models.IntegerField(default=1, null=True, verbose_name='用户类型')),
                ('project_field', models.CharField(default='', max_length=200, verbose_name='可查看的项目')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('token', models.CharField(max_length=50, verbose_name='token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stluser.UserInfo')),
            ],
            options={
                'verbose_name': '用户登陆token',
                'db_table': 'UserToken',
            },
        ),
    ]
